// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5zmIBjk_3ASJn2_i1K213IczxY6t5Cgs',
    appId: '1:968583360677:web:7622fd4bb52de3107b1d4c',
    messagingSenderId: '968583360677',
    projectId: 'pet-shop-notifications',
    authDomain: 'pet-shop-notifications.firebaseapp.com',
    storageBucket: 'pet-shop-notifications.appspot.com',
    measurementId: 'G-5W7M8CNBGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsgMrNFbRar1bUqYWTLnJCCzDi9i-IVpE',
    appId: '1:968583360677:android:0eba958dd9c3a1be7b1d4c',
    messagingSenderId: '968583360677',
    projectId: 'pet-shop-notifications',
    storageBucket: 'pet-shop-notifications.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPCBkLtlAZUcYJz_Yk0YDcSMjzdAbe24U',
    appId: '1:968583360677:ios:a42e4c7d2e15a5837b1d4c',
    messagingSenderId: '968583360677',
    projectId: 'pet-shop-notifications',
    storageBucket: 'pet-shop-notifications.appspot.com',
    iosClientId: '968583360677-hri504v711obrngguqhudqb9vfjlkc25.apps.googleusercontent.com',
    iosBundleId: 'com.example.petShopApp',
  );
}
